version: '3.7'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: php:8.1-fpm
    container_name: play-slim-dice-api
    restart: unless-stopped
    tty: true
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:1.23.1
    container_name: play-slim-dice-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "2080:80"
      - "2443:443"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
